### PR TITLE
Prettify Error message and stack display, fix #32 .

### LINKED ISSUE #32: "no such file or directory" Doesn't Show Errant File/Directory Path
I just got the following error from memory-fs:

    Error: no such file or directory
        at MemoryFileSystem.readFileSync (/myproject/node_modules/memory-fs/lib/MemoryFileSystem.js:108:10)
        at MemoryFileSystem.readFile (/myproject/node_modules/memory-fs/lib/MemoryFileSystem.js:298:21)
        at devRoute (/myproject/backend/webpack.js:36:29)
        at Layer.handle [as handle_request] (/myproject/node_modules/express/lib/router/layer.js:95:5)
        at next (/myproject/node_modules/express/lib/router/route.js:131:13)
        at Route.dispatch (/myproject/node_modules/express/lib/router/route.js:112:3)
        at Layer.handle [as handle_request] (/myproject/node_modules/express/lib/router/layer.js:95:5)
        at /myproject/node_modules/express/lib/router/index.js:277:22
        at Function.process_params (/myproject/node_modules/express/lib/router/index.js:330:12)
        at next (/myproject/node_modules/express/lib/router/index.js:271:10)
        at Layer.handle [as handle_request] (/myproject/node_modules/express/lib/router/layer.js:91:12)
        at trim_prefix (/myproject/node_modules/express/lib/router/index.js:312:13)
        at /myproject/node_modules/express/lib/router/index.js:280:7
        at Function.process_params (/myproject/node_modules/express/lib/router/index.js:330:12)
        at next (/myproject/node_modules/express/lib/router/index.js:271:10)
        at SendStream.error (/myproject/node_modules/serve-static/index.js:121:7)

As you can see, there's no mention of the path it was trying to use to find a file/directory.  However, when I looked at the code it was clear that it intended to share that path:

    if(!isDir(current[path[i]])) 
	    throw new MemoryFileSystemError(errors.code.ENOENT, _path); // Note the ",  _path"

and indeed, if I added a console .log ...

    if(!isDir(current[path[i]])) console.log(_path)

it logged the path successfully.  So evidently there's something wrong with `MemoryFileSystemError` which is causing it to ignore or discard it's second argument.

### PR DESCRIPTION
**Pull request by mc-zone**
### 1. Add path and operation name into error message, make it easier to figure out.

before (`error.message`):
```
no such file or directory
illegal operation on a directory
operation not permitted
file already exists
not a directory
```

after:
```
ENOENT: no such file or directory, unlinkSync '/test/abcd'
EISDIR: illegal operation on a directory, writeFileSync '/test/dir'
EPERM: operation not permitted, rmdirSync '/'
EEXIST: file already exists, mkdirSync '/test/dir'
ENOTDIR: not a directory, mkdirSync '/test/file'
```

### 2. Change first line of stack to use correct message, instance of [object Object].

before (beginning of `error.stack`):
```
Error: [object Object]
    at MemoryFileSystem.readFileSync (...
```

after:
```
MemoryFileSystemError: ENOENT: no such file or directory, readFileSync '/fail/file'
    at MemoryFileSystem.readFileSync ( ...
```

It will fix #32 .

### CODE REVIEW

**Comment by mc-zone** [comment]
Checks list disappeared, what's happen...

**Comment by mc-zone** [comment]
>Coverage decreased (-0.07%) to 96.403%

I've already add the tests. I actually don't know whether I should, and how to cover this 0.07...
But I think it's satisfying for review now. :p @sokra @TheLarkInn

File: lib/MemoryFileSystemError.js [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+
+		// Add operation name into error message, similar to node `fs` style.
+		// It will not exactly same as node `fs`'s result which comes from \
+		// the native call (like `readFile` => `binding.open` => `open`),
+		// but just find out the last method call from the stack.
+		var operation = this.findOperation();
+		if(operation && path) {
+			this.message += `, ${operation} \'${path}\'`;
+		} else if(path) {
+			this.message += `, \'${path}\'`;
```
Comment (sokra) [inline lib/MemoryFileSystemError.js]: This line is not covered. If unused remove it.

File: lib/MemoryFileSystemError.js [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+		}
+		this.code = err.code;
+		this.errno = err.errno;
+		this.path = path;
+
+		if(Error.captureStackTrace) {
+			Error.captureStackTrace(this, this.constructor);
+		}
+	}
+	findOperation() {
```
Comment (sokra) [inline lib/MemoryFileSystemError.js]: Don't do that.

Instead pass the operation name in the error constructor.

Comment (mc-zone) [inline lib/MemoryFileSystemError.js]: Ok, fine.

**Comment by mc-zone** [comment]
Done, review again please. @sokra

File: lib/MemoryFileSystem.js [hunk 3]
```diff
@@ -166,31 +155,31 @@ class MemoryFileSystem {
...
+			throw new MemoryFileSystemError(errors.code.ENOTDIR, _path, "mkdir");
 		current[path[i]] = {"":true};
 		return;
 	}
 
 	_remove(_path, name, testFn) {
 		const path = pathToArray(_path);
 		if(path.length === 0) {
-			throw new MemoryFileSystemError(errors.code.EPERM, _path);
+			throw new MemoryFileSystemError(errors.code.EPERM, _path, "remove");
```
Comment (sokra) [inline lib/MemoryFileSystem.js]: remove is not an operation: pass `rmdir` or `unlink`

Comment (mc-zone) [inline lib/MemoryFileSystem.js]: Fixed. my bad.

File: .eslintrc.json [hunk 4]
```diff
@@ -202,7 +202,6 @@
             "error",
             "always"
         ],
-        "strict": "error",
```
Comment (sokra) [inline .eslintrc.json]: I guess this doesn't have to be removed. You have a `"use strict"` in the file?

Comment (mc-zone) [inline .eslintrc.json]: Yeap, I extracted `MemoryFileSystemError` to a standalone file. So add "use strict" for it's classes declaration, otherwise it will break in node v4.

Comment (mc-zone) [inline .eslintrc.json]: @sokra Does this have any side effects?

**Comment by mc-zone** [comment]
Excuse me, @sokra maybe too busy to notice here?  :smile: 
Must I remove the "use strict"? Could you give any reason? Please.

**Comment by mc-zone** [comment]
uh, so, the codacy can't pass if not removed it...

**Comment by sokra** [comment]
hmmm... weird

**Comment by TheLarkInn** [comment]
Let me disable. 😁

**Comment by sokra** [comment]
Thanks
